trigger:
- main

pool:
  name: Default

steps:
# Build the project
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '/*.csproj'

# Pack the project into NuGet packages
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '/*.csproj'
    versioningScheme: 'byPrereleaseNumber'
    majorVersion: '1'
    minorVersion: '0'
    patchVersion: '0'

# Verify the contents of the build artifact directory (optional for debugging)
- script: |
    echo "Contents of $(Build.ArtifactStagingDirectory):"
    dir "$(Build.ArtifactStagingDirectory)"
  displayName: 'Verify artifact staging directory contents'

# Push the NuGet packages to the Azure Artifacts feed
- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)//*.nupkg;!$(Build.ArtifactStagingDirectory)//*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'Lab4'
