trigger:
- main

pool:
  name: Default

steps:
# Build the project
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'

# Pack the project into NuGet packages
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'byPrereleaseNumber'
    majorVersion: '1'
    minorVersion: '0'
    patchVersion: '0'

# Verify the contents of the build artifact directory (optional for debugging)
- script: |
    echo "Contents of $(Build.ArtifactStagingDirectory):"
    dir "$(Build.ArtifactStagingDirectory)"
  displayName: 'Verify artifact staging directory contents'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: $(SYSTEM_ACCESSTOKEN)
    publishFeedUri: 'https://pkgs.dev.azure.com/S8G32H/Lab4/_packaging/Lab4/nuget/v3/index.json'
