trigger:
- main # Adjust the branch name as needed

pool:
  vmImage: 'windows-latest' # Use a Microsoft-hosted agent with Windows

steps:
# 1. Install NuGet CLI
- task: UseNuGet@5
  displayName: 'Install NuGet CLI'
  inputs:
    version: 'latest'

# 2. Authenticate with the Azure Artifacts feed
- task: NuGetAuthenticate@1
  displayName: 'Authenticate with Azure Artifacts'

# 3. Restore NuGet packages using the feed
- task: NuGetCommand@2
  displayName: 'Restore NuGet Packages'
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln' # Path to your solution file
    feedsToUse: 'select'
    vstsFeed: 'S8G32H/Lab4/Lab4'

# 4. Build the solution
- task: VSBuild@1
  displayName: 'Build Solution'
  inputs:
    solution: '**/*.sln'
    msbuildArchitecture: 'x64'

# 5. Publish artifacts (optional, if you're building a package)
- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'
