name: '$(Build.DefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)'

trigger:
- main  # Adjust this to your default branch

pool:
  name: 'Default'  # Replace with your self-hosted agent pool name

variables:
  buildConfiguration: 'Release'
  nugetFeed: 'https://pkgs.dev.azure.com/S8G32H/Lab4/_packaging/Lab4/nuget/v3/index.json'
  packageName: 'StringExtensions'  # Package name
  apiKey: '3SHrQ9nijjlpY5z8gAiIFy53G5Xxvgr9GvjaPkW1BdI4TSagGnrhJQQJ99AKACAAAAAnPw96AAASAZDOS9EZ'  # Replace with your actual Azure Artifacts API key

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'byBuildNumber'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

- script: |
    echo "Listing contents of $(Build.ArtifactStagingDirectory):"
    ls $(Build.ArtifactStagingDirectory)
  displayName: 'List Artifact Staging Directory'

- task: DotNetCoreCLI@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'external'  # Use 'external' for Azure Artifacts feed
    publishVstsFeed: ''  # Leave empty since we are not using a service connection
    arguments: '--api-key $(apiKey)'  # Pass the API key directly here

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'NuGetPackages'
