# azure-pipelines.yml
trigger:
  branches:
    include:
      - main  # Adjust this to your main branch name

pool:
  vmImage: 'windows-latest'  # Use a self-hosted agent if necessary

steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet packages'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build the project'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  displayName: 'Pack the project'
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'byBuildNumber'
    configuration: 'Release'

- task: DotNetCoreCLI@2
  displayName: 'Push NuGet package to Azure Artifacts'
  inputs:
    command: 'push'
    packagesToPush: '**/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'Lab4'  # Replace with your Azure Artifacts feed name
    allowPackageConflicts: true

- task: PublishPipelineArtifact@1
  displayName: 'Publish NuGet package as artifact'
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifactName: 'NuGetPackages'
